version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/anime_db
      - JWT_SECRET=devsecret
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=devpass
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
